/* soapStub.h
   Generated by gSOAP 2.8.17r from cwmp-1-4.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapStub_H
#define soapStub_H
#define SOAP_NAMESPACE_OF_ns1	"urn:dslforum-org:cwmp-1-2"
#include "stdsoap2.h"
#if GSOAP_VERSION != 20817
# error "GSOAP VERSION MISMATCH IN GENERATED CODE: PLEASE REINSTALL PACKAGE"
#endif

#ifdef __cplusplus
extern "C" {
#endif

/******************************************************************************\
 *                                                                            *
 * Enumerations                                                               *
 *                                                                            *
\******************************************************************************/


#ifndef SOAP_TYPE_xsd__boolean
#define SOAP_TYPE_xsd__boolean (11)
/* xsd:boolean */
enum xsd__boolean { xsd__boolean__false_ = 0, xsd__boolean__true_ = 1 };
#endif

#ifndef SOAP_TYPE_ns1__AccessListValueType
#define SOAP_TYPE_ns1__AccessListValueType (28)
/* ns1:AccessListValueType */
enum ns1__AccessListValueType { ns1__AccessListValueType__Subscriber = 0 };
#endif

#ifndef SOAP_TYPE_ns1__ParameterAttributeNotificationValueType
#define SOAP_TYPE_ns1__ParameterAttributeNotificationValueType (29)
/* ns1:ParameterAttributeNotificationValueType */
enum ns1__ParameterAttributeNotificationValueType { ns1__ParameterAttributeNotificationValueType__0 = 0, ns1__ParameterAttributeNotificationValueType__1 = 1, ns1__ParameterAttributeNotificationValueType__2 = 2, ns1__ParameterAttributeNotificationValueType__3 = 3, ns1__ParameterAttributeNotificationValueType__4 = 4, ns1__ParameterAttributeNotificationValueType__5 = 5, ns1__ParameterAttributeNotificationValueType__6 = 6 };
#endif

#ifndef SOAP_TYPE_ns1__TransferStateType
#define SOAP_TYPE_ns1__TransferStateType (30)
/* ns1:TransferStateType */
enum ns1__TransferStateType { ns1__TransferStateType__1 = 1, ns1__TransferStateType__2 = 2, ns1__TransferStateType__3 = 3 };
#endif

#ifndef SOAP_TYPE_ns1__DeploymentUnitState
#define SOAP_TYPE_ns1__DeploymentUnitState (32)
/* ns1:DeploymentUnitState */
enum ns1__DeploymentUnitState { ns1__DeploymentUnitState__Installed = 0, ns1__DeploymentUnitState__Uninstalled = 1, ns1__DeploymentUnitState__Failed = 2 };
#endif

#ifndef SOAP_TYPE_ns1__DefaultDeploymentUnitOperationType
#define SOAP_TYPE_ns1__DefaultDeploymentUnitOperationType (33)
/* ns1:DefaultDeploymentUnitOperationType */
enum ns1__DefaultDeploymentUnitOperationType { ns1__DefaultDeploymentUnitOperationType__Install = 0, ns1__DefaultDeploymentUnitOperationType__Update = 1, ns1__DefaultDeploymentUnitOperationType__Uninstall = 2 };
#endif

#ifndef SOAP_TYPE_ns1__TransferCompleteCPEFaultCodeType
#define SOAP_TYPE_ns1__TransferCompleteCPEFaultCodeType (34)
/* ns1:TransferCompleteCPEFaultCodeType */
enum ns1__TransferCompleteCPEFaultCodeType { ns1__TransferCompleteCPEFaultCodeType__9001 = 9001, ns1__TransferCompleteCPEFaultCodeType__9002 = 9002, ns1__TransferCompleteCPEFaultCodeType__9010 = 9010, ns1__TransferCompleteCPEFaultCodeType__9011 = 9011, ns1__TransferCompleteCPEFaultCodeType__9012 = 9012, ns1__TransferCompleteCPEFaultCodeType__9014 = 9014, ns1__TransferCompleteCPEFaultCodeType__9015 = 9015, ns1__TransferCompleteCPEFaultCodeType__9016 = 9016, ns1__TransferCompleteCPEFaultCodeType__9017 = 9017, ns1__TransferCompleteCPEFaultCodeType__9018 = 9018, ns1__TransferCompleteCPEFaultCodeType__9019 = 9019, ns1__TransferCompleteCPEFaultCodeType__9020 = 9020 };
#endif

#ifndef SOAP_TYPE_ns1__DeploymentUnitCPEFaultCodeType
#define SOAP_TYPE_ns1__DeploymentUnitCPEFaultCodeType (35)
/* ns1:DeploymentUnitCPEFaultCodeType */
enum ns1__DeploymentUnitCPEFaultCodeType { ns1__DeploymentUnitCPEFaultCodeType__9001 = 9001, ns1__DeploymentUnitCPEFaultCodeType__9003 = 9003, ns1__DeploymentUnitCPEFaultCodeType__9012 = 9012, ns1__DeploymentUnitCPEFaultCodeType__9013 = 9013, ns1__DeploymentUnitCPEFaultCodeType__9015 = 9015, ns1__DeploymentUnitCPEFaultCodeType__9016 = 9016, ns1__DeploymentUnitCPEFaultCodeType__9017 = 9017, ns1__DeploymentUnitCPEFaultCodeType__9018 = 9018, ns1__DeploymentUnitCPEFaultCodeType__9022 = 9022, ns1__DeploymentUnitCPEFaultCodeType__9023 = 9023, ns1__DeploymentUnitCPEFaultCodeType__9024 = 9024, ns1__DeploymentUnitCPEFaultCodeType__9025 = 9025, ns1__DeploymentUnitCPEFaultCodeType__9026 = 9026, ns1__DeploymentUnitCPEFaultCodeType__9027 = 9027, ns1__DeploymentUnitCPEFaultCodeType__9028 = 9028, ns1__DeploymentUnitCPEFaultCodeType__9029 = 9029, ns1__DeploymentUnitCPEFaultCodeType__9030 = 9030, ns1__DeploymentUnitCPEFaultCodeType__9031 = 9031, ns1__DeploymentUnitCPEFaultCodeType__9032 = 9032 };
#endif

#ifndef SOAP_TYPE__ns1__OptionStruct_State
#define SOAP_TYPE__ns1__OptionStruct_State (54)
/* ns1:OptionStruct-State */
enum _ns1__OptionStruct_State { _ns1__OptionStruct_State__0 = 0, _ns1__OptionStruct_State__1 = 1, _ns1__OptionStruct_State__2 = 2, _ns1__OptionStruct_State__3 = 3 };
#endif

#ifndef SOAP_TYPE__ns1__OptionStruct_Mode
#define SOAP_TYPE__ns1__OptionStruct_Mode (55)
/* ns1:OptionStruct-Mode */
enum _ns1__OptionStruct_Mode { _ns1__OptionStruct_Mode__0 = 0, _ns1__OptionStruct_Mode__1 = 1, _ns1__OptionStruct_Mode__2 = 2 };
#endif

#ifndef SOAP_TYPE__ns1__OptionStruct_IsTransferable
#define SOAP_TYPE__ns1__OptionStruct_IsTransferable (57)
/* ns1:OptionStruct-IsTransferable */
enum _ns1__OptionStruct_IsTransferable { _ns1__OptionStruct_IsTransferable__0 = 0, _ns1__OptionStruct_IsTransferable__1 = 1 };
#endif

#ifndef SOAP_TYPE__ns1__SetParameterValuesResponse_Status
#define SOAP_TYPE__ns1__SetParameterValuesResponse_Status (70)
/* ns1:SetParameterValuesResponse-Status */
enum _ns1__SetParameterValuesResponse_Status { _ns1__SetParameterValuesResponse_Status__0 = 0, _ns1__SetParameterValuesResponse_Status__1 = 1 };
#endif

#ifndef SOAP_TYPE__ns1__AddObjectResponse_Status
#define SOAP_TYPE__ns1__AddObjectResponse_Status (89)
/* ns1:AddObjectResponse-Status */
enum _ns1__AddObjectResponse_Status { _ns1__AddObjectResponse_Status__0 = 0, _ns1__AddObjectResponse_Status__1 = 1 };
#endif

#ifndef SOAP_TYPE__ns1__DeleteObjectResponse_Status
#define SOAP_TYPE__ns1__DeleteObjectResponse_Status (92)
/* ns1:DeleteObjectResponse-Status */
enum _ns1__DeleteObjectResponse_Status { _ns1__DeleteObjectResponse_Status__0 = 0, _ns1__DeleteObjectResponse_Status__1 = 1 };
#endif

#ifndef SOAP_TYPE__ns1__DownloadResponse_Status
#define SOAP_TYPE__ns1__DownloadResponse_Status (95)
/* ns1:DownloadResponse-Status */
enum _ns1__DownloadResponse_Status { _ns1__DownloadResponse_Status__0 = 0, _ns1__DownloadResponse_Status__1 = 1 };
#endif

#ifndef SOAP_TYPE__ns1__UploadResponse_Status
#define SOAP_TYPE__ns1__UploadResponse_Status (114)
/* ns1:UploadResponse-Status */
enum _ns1__UploadResponse_Status { _ns1__UploadResponse_Status__0 = 0, _ns1__UploadResponse_Status__1 = 1 };
#endif

/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Classes and Structs                                                        *
 *                                                                            *
\******************************************************************************/


#if 0 /* volatile type: do not declare here, declared elsewhere */

#endif

#ifndef SOAP_TYPE_SOAP_ENC__base64
#define SOAP_TYPE_SOAP_ENC__base64 (7)
/* Base64 schema type: */
struct SOAP_ENC__base64
{
	unsigned char *__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_ns1__TransferCompleteFaultStruct
#define SOAP_TYPE_ns1__TransferCompleteFaultStruct (36)
/* ns1:TransferCompleteFaultStruct */
struct ns1__TransferCompleteFaultStruct
{
	char *FaultCode;	/* required element of type xsd:string */
	char *FaultString;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__DeploymentUnitFaultStruct
#define SOAP_TYPE_ns1__DeploymentUnitFaultStruct (37)
/* ns1:DeploymentUnitFaultStruct */
struct ns1__DeploymentUnitFaultStruct
{
	char *FaultCode;	/* required element of type xsd:string */
	char *FaultString;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__ParameterValueStruct
#define SOAP_TYPE_ns1__ParameterValueStruct (38)
/* ns1:ParameterValueStruct */
struct ns1__ParameterValueStruct
{
	char *Name;	/* required element of type xsd:string */
	char *Value;	/* required element of type xsd:anySimpleType */
};
#endif

#ifndef SOAP_TYPE_ns1__DeviceIdStruct
#define SOAP_TYPE_ns1__DeviceIdStruct (39)
/* ns1:DeviceIdStruct */
struct ns1__DeviceIdStruct
{
	char *Manufacturer;	/* required element of type xsd:string */
	char *OUI;	/* required element of type xsd:string */
	char *ProductClass;	/* required element of type xsd:string */
	char *SerialNumber;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__EventStruct
#define SOAP_TYPE_ns1__EventStruct (40)
/* ns1:EventStruct */
struct ns1__EventStruct
{
	char *EventCode;	/* required element of type ns1:EventCodeType */
	char *CommandKey;	/* required element of type ns1:CommandKeyType */
};
#endif

#ifndef SOAP_TYPE_ns1__ParameterInfoStruct
#define SOAP_TYPE_ns1__ParameterInfoStruct (41)
/* ns1:ParameterInfoStruct */
struct ns1__ParameterInfoStruct
{
	char *Name;	/* required element of type xsd:string */
	enum xsd__boolean Writable;	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_ns1__SetParameterAttributesStruct
#define SOAP_TYPE_ns1__SetParameterAttributesStruct (42)
/* ns1:SetParameterAttributesStruct */
struct ns1__SetParameterAttributesStruct
{
	char *Name;	/* required element of type xsd:string */
	enum xsd__boolean NotificationChange;	/* required element of type xsd:boolean */
	enum ns1__ParameterAttributeNotificationValueType Notification;	/* required element of type ns1:ParameterAttributeNotificationValueType */
	enum xsd__boolean AccessListChange;	/* required element of type xsd:boolean */
	struct AccessList *AccessList;	/* required element of type ArrayOfAccessListValueType */
};
#endif

#ifndef SOAP_TYPE_ns1__ParameterAttributeStruct
#define SOAP_TYPE_ns1__ParameterAttributeStruct (45)
/* ns1:ParameterAttributeStruct */
struct ns1__ParameterAttributeStruct
{
	char *Name;	/* required element of type xsd:string */
	enum ns1__ParameterAttributeNotificationValueType Notification;	/* required element of type ns1:ParameterAttributeNotificationValueType */
	struct AccessList *AccessList;	/* required element of type ArrayOfAccessListValueType */
};
#endif

#ifndef SOAP_TYPE_ns1__TimeWindowStruct
#define SOAP_TYPE_ns1__TimeWindowStruct (46)
/* ns1:TimeWindowStruct */
struct ns1__TimeWindowStruct
{
	unsigned int WindowStart;	/* required element of type xsd:unsignedInt */
	unsigned int WindowEnd;	/* required element of type xsd:unsignedInt */
	char *WindowMode;	/* required element of type ns1:TimeWindowModeValueType */
	char *UserMessage;	/* required element of type xsd:string */
	int MaxRetries;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns1__QueuedTransferStruct
#define SOAP_TYPE_ns1__QueuedTransferStruct (47)
/* ns1:QueuedTransferStruct */
struct ns1__QueuedTransferStruct
{
	char *CommandKey;	/* required element of type ns1:CommandKeyType */
	enum ns1__TransferStateType State;	/* required element of type ns1:TransferStateType */
};
#endif

#ifndef SOAP_TYPE_ns1__AllQueuedTransferStruct
#define SOAP_TYPE_ns1__AllQueuedTransferStruct (48)
/* ns1:AllQueuedTransferStruct */
struct ns1__AllQueuedTransferStruct
{
	char *CommandKey;	/* required element of type ns1:CommandKeyType */
	enum ns1__TransferStateType State;	/* required element of type ns1:TransferStateType */
	enum xsd__boolean IsDownload;	/* required element of type xsd:boolean */
	char *FileType;	/* required element of type ns1:TransferFileType */
	unsigned int FileSize;	/* required element of type xsd:unsignedInt */
	char *TargetFileName;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__OperationStruct
#define SOAP_TYPE_ns1__OperationStruct (49)
/* ns1:OperationStruct */
struct ns1__OperationStruct
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE_ns1__OpResultStruct
#define SOAP_TYPE_ns1__OpResultStruct (50)
/* ns1:OpResultStruct */
struct ns1__OpResultStruct
{
	char *UUID;	/* required element of type ns1:DeploymentUnitUUID */
	char *DeploymentUnitRef;	/* required element of type xsd:string */
	char *Version;	/* required element of type xsd:string */
	enum ns1__DeploymentUnitState CurrentState;	/* required element of type ns1:DeploymentUnitState */
	enum xsd__boolean Resolved;	/* required element of type xsd:boolean */
	char *ExecutionUnitRefList;	/* required element of type xsd:string */
	time_t StartTime;	/* required element of type xsd:dateTime */
	time_t CompleteTime;	/* required element of type xsd:dateTime */
	struct ns1__DeploymentUnitFaultStruct *Fault;	/* required element of type ns1:DeploymentUnitFaultStruct */
};
#endif

#ifndef SOAP_TYPE_ns1__OptionStruct
#define SOAP_TYPE_ns1__OptionStruct (53)
/* ns1:OptionStruct */
struct ns1__OptionStruct
{
	char *OptionName;	/* required element of type xsd:string */
	unsigned int VoucherSN;	/* required element of type xsd:unsignedInt */
	enum _ns1__OptionStruct_State State;	/* required element of type ns1:OptionStruct-State */
	enum _ns1__OptionStruct_Mode Mode;	/* required element of type ns1:OptionStruct-Mode */
	time_t StartDate;	/* required element of type xsd:dateTime */
	time_t *ExpirationDate;	/* optional element of type xsd:dateTime */
	enum _ns1__OptionStruct_IsTransferable IsTransferable;	/* required element of type ns1:OptionStruct-IsTransferable */
};
#endif

#ifndef SOAP_TYPE_ns1__ArgStruct
#define SOAP_TYPE_ns1__ArgStruct (58)
/* ns1:ArgStruct */
struct ns1__ArgStruct
{
	char *Name;	/* required element of type xsd:string */
	char *Value;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__Fault_SetParameterValuesFault
#define SOAP_TYPE__ns1__Fault_SetParameterValuesFault (60)
/* ns1:Fault-SetParameterValuesFault */
struct _ns1__Fault_SetParameterValuesFault
{
	char *ParameterName;	/* required element of type xsd:string */
	char *FaultCode;	/* required element of type xsd:string */
	char *FaultString;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__Fault
#define SOAP_TYPE__ns1__Fault (59)
/* ns1:Fault */
struct _ns1__Fault
{
	char *FaultCode;	/* required element of type xsd:string */
	char *FaultString;	/* optional element of type xsd:string */
	int __sizeSetParameterValuesFault;	/* sequence of elements <SetParameterValuesFault> */
	struct _ns1__Fault_SetParameterValuesFault *SetParameterValuesFault;	/* optional element of type ns1:Fault-SetParameterValuesFault */
};
#endif

#ifndef SOAP_TYPE__ns1__GetRPCMethods
#define SOAP_TYPE__ns1__GetRPCMethods (62)
/* ns1:GetRPCMethods */
struct _ns1__GetRPCMethods
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__ns1__GetRPCMethodsResponse
#define SOAP_TYPE__ns1__GetRPCMethodsResponse (63)
/* ns1:GetRPCMethodsResponse */
struct _ns1__GetRPCMethodsResponse
{
	struct MethodList *MethodList;	/* required element of type ArrayOfstring */
};
#endif

#ifndef SOAP_TYPE__ns1__SetParameterValues
#define SOAP_TYPE__ns1__SetParameterValues (66)
/* ns1:SetParameterValues */
struct _ns1__SetParameterValues
{
	struct ParameterValueList *ParameterList;	/* required element of type ArrayOfParameterValueStruct */
	char *ParameterKey;	/* required element of type ns1:ParameterKeyType */
};
#endif

#ifndef SOAP_TYPE__ns1__SetParameterValuesResponse
#define SOAP_TYPE__ns1__SetParameterValuesResponse (69)
/* ns1:SetParameterValuesResponse */
struct _ns1__SetParameterValuesResponse
{
	enum _ns1__SetParameterValuesResponse_Status Status;	/* required element of type ns1:SetParameterValuesResponse-Status */
};
#endif

#ifndef SOAP_TYPE__ns1__GetParameterValues
#define SOAP_TYPE__ns1__GetParameterValues (71)
/* ns1:GetParameterValues */
struct _ns1__GetParameterValues
{
	struct ParameterNames *ParameterNames;	/* required element of type ArrayOfstring */
};
#endif

#ifndef SOAP_TYPE__ns1__GetParameterValuesResponse
#define SOAP_TYPE__ns1__GetParameterValuesResponse (74)
/* ns1:GetParameterValuesResponse */
struct _ns1__GetParameterValuesResponse
{
	struct ParameterValueList *ParameterList;	/* required element of type ArrayOfParameterValueStruct */
};
#endif

#ifndef SOAP_TYPE__ns1__GetParameterNames
#define SOAP_TYPE__ns1__GetParameterNames (75)
/* ns1:GetParameterNames */
struct _ns1__GetParameterNames
{
	char *ParameterPath;	/* required element of type xsd:string */
	enum xsd__boolean NextLevel;	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE__ns1__GetParameterNamesResponse
#define SOAP_TYPE__ns1__GetParameterNamesResponse (76)
/* ns1:GetParameterNamesResponse */
struct _ns1__GetParameterNamesResponse
{
	struct ParameterInfoList *ParameterList;	/* required element of type ArrayOfParameterInfoStruct */
};
#endif

#ifndef SOAP_TYPE__ns1__SetParameterAttributes
#define SOAP_TYPE__ns1__SetParameterAttributes (79)
/* ns1:SetParameterAttributes */
struct _ns1__SetParameterAttributes
{
	struct SetParameterAttributesList *ParameterList;	/* required element of type ArrayOfSetParameterAttributesStruct */
};
#endif

#ifndef SOAP_TYPE__ns1__SetParameterAttributesResponse
#define SOAP_TYPE__ns1__SetParameterAttributesResponse (82)
/* ns1:SetParameterAttributesResponse */
struct _ns1__SetParameterAttributesResponse
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__ns1__GetParameterAttributes
#define SOAP_TYPE__ns1__GetParameterAttributes (83)
/* ns1:GetParameterAttributes */
struct _ns1__GetParameterAttributes
{
	struct ParameterNames *ParameterNames;	/* required element of type ArrayOfstring */
};
#endif

#ifndef SOAP_TYPE__ns1__GetParameterAttributesResponse
#define SOAP_TYPE__ns1__GetParameterAttributesResponse (84)
/* ns1:GetParameterAttributesResponse */
struct _ns1__GetParameterAttributesResponse
{
	struct ParameterAttributeList *ParameterList;	/* required element of type ArrayOfParameterAttributeStruct */
};
#endif

#ifndef SOAP_TYPE__ns1__AddObject
#define SOAP_TYPE__ns1__AddObject (87)
/* ns1:AddObject */
struct _ns1__AddObject
{
	char *ObjectName;	/* required element of type ns1:ObjectNameType */
	char *ParameterKey;	/* required element of type ns1:ParameterKeyType */
};
#endif

#ifndef SOAP_TYPE__ns1__AddObjectResponse
#define SOAP_TYPE__ns1__AddObjectResponse (88)
/* ns1:AddObjectResponse */
struct _ns1__AddObjectResponse
{
	unsigned int InstanceNumber;	/* required element of type xsd:unsignedInt */
	enum _ns1__AddObjectResponse_Status Status;	/* required element of type ns1:AddObjectResponse-Status */
};
#endif

#ifndef SOAP_TYPE__ns1__DeleteObject
#define SOAP_TYPE__ns1__DeleteObject (90)
/* ns1:DeleteObject */
struct _ns1__DeleteObject
{
	char *ObjectName;	/* required element of type ns1:ObjectNameType */
	char *ParameterKey;	/* required element of type ns1:ParameterKeyType */
};
#endif

#ifndef SOAP_TYPE__ns1__DeleteObjectResponse
#define SOAP_TYPE__ns1__DeleteObjectResponse (91)
/* ns1:DeleteObjectResponse */
struct _ns1__DeleteObjectResponse
{
	enum _ns1__DeleteObjectResponse_Status Status;	/* required element of type ns1:DeleteObjectResponse-Status */
};
#endif

#ifndef SOAP_TYPE__ns1__Download
#define SOAP_TYPE__ns1__Download (93)
/* ns1:Download */
struct _ns1__Download
{
	char *CommandKey;	/* required element of type ns1:CommandKeyType */
	char *FileType;	/* required element of type ns1:DownloadFileType */
	char *URL;	/* required element of type xsd:string */
	char *Username;	/* required element of type xsd:string */
	char *Password;	/* required element of type xsd:string */
	unsigned int FileSize;	/* required element of type xsd:unsignedInt */
	char *TargetFileName;	/* required element of type xsd:string */
	unsigned int DelaySeconds;	/* required element of type xsd:unsignedInt */
	char *SuccessURL;	/* required element of type xsd:string */
	char *FailureURL;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__DownloadResponse
#define SOAP_TYPE__ns1__DownloadResponse (94)
/* ns1:DownloadResponse */
struct _ns1__DownloadResponse
{
	enum _ns1__DownloadResponse_Status Status;	/* required element of type ns1:DownloadResponse-Status */
	time_t StartTime;	/* required element of type xsd:dateTime */
	time_t CompleteTime;	/* required element of type xsd:dateTime */
};
#endif

#ifndef SOAP_TYPE__ns1__Reboot
#define SOAP_TYPE__ns1__Reboot (96)
/* ns1:Reboot */
struct _ns1__Reboot
{
	char *CommandKey;	/* required element of type ns1:CommandKeyType */
};
#endif

#ifndef SOAP_TYPE__ns1__RebootResponse
#define SOAP_TYPE__ns1__RebootResponse (97)
/* ns1:RebootResponse */
struct _ns1__RebootResponse
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__ns1__GetQueuedTransfers
#define SOAP_TYPE__ns1__GetQueuedTransfers (98)
/* ns1:GetQueuedTransfers */
struct _ns1__GetQueuedTransfers
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__ns1__GetQueuedTransfersResponse
#define SOAP_TYPE__ns1__GetQueuedTransfersResponse (99)
/* ns1:GetQueuedTransfersResponse */
struct _ns1__GetQueuedTransfersResponse
{
	struct TransferList *TransferList;	/* required element of type ArrayOfQueuedTransferStruct */
};
#endif

#ifndef SOAP_TYPE__ns1__ScheduleInform
#define SOAP_TYPE__ns1__ScheduleInform (102)
/* ns1:ScheduleInform */
struct _ns1__ScheduleInform
{
	unsigned int DelaySeconds;	/* required element of type xsd:unsignedInt */
	char *CommandKey;	/* required element of type ns1:CommandKeyType */
};
#endif

#ifndef SOAP_TYPE__ns1__ScheduleInformResponse
#define SOAP_TYPE__ns1__ScheduleInformResponse (103)
/* ns1:ScheduleInformResponse */
struct _ns1__ScheduleInformResponse
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__ns1__SetVouchers
#define SOAP_TYPE__ns1__SetVouchers (104)
/* ns1:SetVouchers */
struct _ns1__SetVouchers
{
	struct VoucherList *VoucherList;	/* required element of type ArrayOfbase64 */
};
#endif

#ifndef SOAP_TYPE__ns1__SetVouchersResponse
#define SOAP_TYPE__ns1__SetVouchersResponse (107)
/* ns1:SetVouchersResponse */
struct _ns1__SetVouchersResponse
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__ns1__GetOptions
#define SOAP_TYPE__ns1__GetOptions (108)
/* ns1:GetOptions */
struct _ns1__GetOptions
{
	char *OptionName;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__GetOptionsResponse
#define SOAP_TYPE__ns1__GetOptionsResponse (109)
/* ns1:GetOptionsResponse */
struct _ns1__GetOptionsResponse
{
	struct OptionList *OptionList;	/* required element of type ArrayOfOptionStruct */
};
#endif

#ifndef SOAP_TYPE__ns1__Upload
#define SOAP_TYPE__ns1__Upload (112)
/* ns1:Upload */
struct _ns1__Upload
{
	char *CommandKey;	/* required element of type ns1:CommandKeyType */
	char *FileType;	/* required element of type ns1:UploadFileType */
	char *URL;	/* required element of type xsd:string */
	char *Username;	/* required element of type xsd:string */
	char *Password;	/* required element of type xsd:string */
	unsigned int DelaySeconds;	/* required element of type xsd:unsignedInt */
};
#endif

#ifndef SOAP_TYPE__ns1__UploadResponse
#define SOAP_TYPE__ns1__UploadResponse (113)
/* ns1:UploadResponse */
struct _ns1__UploadResponse
{
	enum _ns1__UploadResponse_Status Status;	/* required element of type ns1:UploadResponse-Status */
	time_t StartTime;	/* required element of type xsd:dateTime */
	time_t CompleteTime;	/* required element of type xsd:dateTime */
};
#endif

#ifndef SOAP_TYPE__ns1__FactoryReset
#define SOAP_TYPE__ns1__FactoryReset (115)
/* ns1:FactoryReset */
struct _ns1__FactoryReset
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__ns1__FactoryResetResponse
#define SOAP_TYPE__ns1__FactoryResetResponse (116)
/* ns1:FactoryResetResponse */
struct _ns1__FactoryResetResponse
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__ns1__GetAllQueuedTransfers
#define SOAP_TYPE__ns1__GetAllQueuedTransfers (117)
/* ns1:GetAllQueuedTransfers */
struct _ns1__GetAllQueuedTransfers
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__ns1__GetAllQueuedTransfersResponse
#define SOAP_TYPE__ns1__GetAllQueuedTransfersResponse (118)
/* ns1:GetAllQueuedTransfersResponse */
struct _ns1__GetAllQueuedTransfersResponse
{
	struct AllTransferList *TransferList;	/* required element of type ArrayOfAllQueuedTransferStruct */
};
#endif

#ifndef SOAP_TYPE__ns1__ScheduleDownload
#define SOAP_TYPE__ns1__ScheduleDownload (121)
/* ns1:ScheduleDownload */
struct _ns1__ScheduleDownload
{
	char *CommandKey;	/* required element of type ns1:CommandKeyType */
	char *FileType;	/* required element of type ns1:DownloadFileType */
	char *URL;	/* required element of type xsd:string */
	char *Username;	/* required element of type xsd:string */
	char *Password;	/* required element of type xsd:string */
	unsigned int FileSize;	/* required element of type xsd:unsignedInt */
	char *TargetFileName;	/* required element of type xsd:string */
	struct TimeWindowList *TimeWindowList;	/* required element of type ArrayOfTimeWindowStruct */
};
#endif

#ifndef SOAP_TYPE__ns1__ScheduleDownloadResponse
#define SOAP_TYPE__ns1__ScheduleDownloadResponse (124)
/* ns1:ScheduleDownloadResponse */
struct _ns1__ScheduleDownloadResponse
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__ns1__CancelTransfer
#define SOAP_TYPE__ns1__CancelTransfer (125)
/* ns1:CancelTransfer */
struct _ns1__CancelTransfer
{
	char *CommandKey;	/* required element of type ns1:CommandKeyType */
};
#endif

#ifndef SOAP_TYPE__ns1__CancelTransferResponse
#define SOAP_TYPE__ns1__CancelTransferResponse (126)
/* ns1:CancelTransferResponse */
struct _ns1__CancelTransferResponse
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__ns1__ChangeDUState
#define SOAP_TYPE__ns1__ChangeDUState (127)
/* ns1:ChangeDUState */
struct _ns1__ChangeDUState
{
	int __sizeOperations;	/* sequence of elements <Operations> */
	struct ns1__OperationStruct *Operations;	/* required element of type ns1:OperationStruct */
	char *CommandKey;	/* optional element of type ns1:CommandKeyType */
};
#endif

#ifndef SOAP_TYPE__ns1__ChangeDUStateResponse
#define SOAP_TYPE__ns1__ChangeDUStateResponse (129)
/* ns1:ChangeDUStateResponse */
struct _ns1__ChangeDUStateResponse
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__ns1__Inform
#define SOAP_TYPE__ns1__Inform (130)
/* ns1:Inform */
struct _ns1__Inform
{
	struct ns1__DeviceIdStruct *DeviceId;	/* required element of type ns1:DeviceIdStruct */
	struct EventList *Event;	/* required element of type ArrayOfEventStruct */
	unsigned int MaxEnvelopes;	/* required element of type xsd:unsignedInt */
	time_t CurrentTime;	/* required element of type xsd:dateTime */
	unsigned int RetryCount;	/* required element of type xsd:unsignedInt */
	struct ParameterValueList *ParameterList;	/* required element of type ArrayOfParameterValueStruct */
};
#endif

#ifndef SOAP_TYPE__ns1__InformResponse
#define SOAP_TYPE__ns1__InformResponse (134)
/* ns1:InformResponse */
struct _ns1__InformResponse
{
	unsigned int MaxEnvelopes;	/* required element of type xsd:unsignedInt */
};
#endif

#ifndef SOAP_TYPE__ns1__TransferComplete
#define SOAP_TYPE__ns1__TransferComplete (135)
/* ns1:TransferComplete */
struct _ns1__TransferComplete
{
	char *CommandKey;	/* required element of type ns1:CommandKeyType */
	struct ns1__TransferCompleteFaultStruct *FaultStruct;	/* required element of type ns1:TransferCompleteFaultStruct */
	time_t StartTime;	/* required element of type xsd:dateTime */
	time_t CompleteTime;	/* required element of type xsd:dateTime */
};
#endif

#ifndef SOAP_TYPE__ns1__TransferCompleteResponse
#define SOAP_TYPE__ns1__TransferCompleteResponse (137)
/* ns1:TransferCompleteResponse */
struct _ns1__TransferCompleteResponse
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__ns1__AutonomousTransferComplete
#define SOAP_TYPE__ns1__AutonomousTransferComplete (138)
/* ns1:AutonomousTransferComplete */
struct _ns1__AutonomousTransferComplete
{
	char *AnnounceURL;	/* required element of type xsd:string */
	char *TransferURL;	/* required element of type xsd:string */
	enum xsd__boolean IsDownload;	/* required element of type xsd:boolean */
	char *FileType;	/* required element of type ns1:TransferFileType */
	unsigned int FileSize;	/* required element of type xsd:unsignedInt */
	char *TargetFileName;	/* required element of type xsd:string */
	struct ns1__TransferCompleteFaultStruct *FaultStruct;	/* required element of type ns1:TransferCompleteFaultStruct */
	time_t StartTime;	/* required element of type xsd:dateTime */
	time_t CompleteTime;	/* required element of type xsd:dateTime */
};
#endif

#ifndef SOAP_TYPE__ns1__AutonomousTransferCompleteResponse
#define SOAP_TYPE__ns1__AutonomousTransferCompleteResponse (139)
/* ns1:AutonomousTransferCompleteResponse */
struct _ns1__AutonomousTransferCompleteResponse
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__ns1__Kicked
#define SOAP_TYPE__ns1__Kicked (140)
/* ns1:Kicked */
struct _ns1__Kicked
{
	char *Command;	/* required element of type xsd:string */
	char *Referer;	/* required element of type xsd:string */
	char *Arg;	/* required element of type xsd:string */
	char *Next;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__KickedResponse
#define SOAP_TYPE__ns1__KickedResponse (141)
/* ns1:KickedResponse */
struct _ns1__KickedResponse
{
	char *NextURL;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__RequestDownload
#define SOAP_TYPE__ns1__RequestDownload (142)
/* ns1:RequestDownload */
struct _ns1__RequestDownload
{
	char *FileType;	/* required element of type ns1:DownloadFileType */
	struct FileTypeArg *FileTypeArg;	/* required element of type ArrayOfArgStruct */
};
#endif

#ifndef SOAP_TYPE__ns1__RequestDownloadResponse
#define SOAP_TYPE__ns1__RequestDownloadResponse (145)
/* ns1:RequestDownloadResponse */
struct _ns1__RequestDownloadResponse
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__ns1__DUStateChangeComplete
#define SOAP_TYPE__ns1__DUStateChangeComplete (146)
/* ns1:DUStateChangeComplete */
struct _ns1__DUStateChangeComplete
{
	int __sizeResults;	/* sequence of elements <Results> */
	struct ns1__OpResultStruct *Results;	/* required element of type ns1:OpResultStruct */
	char *CommandKey;	/* optional element of type ns1:CommandKeyType */
};
#endif

#ifndef SOAP_TYPE__ns1__DUStateChangeCompleteResponse
#define SOAP_TYPE__ns1__DUStateChangeCompleteResponse (148)
/* ns1:DUStateChangeCompleteResponse */
struct _ns1__DUStateChangeCompleteResponse
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__ns1__AutonomousDUStateChangeComplete
#define SOAP_TYPE__ns1__AutonomousDUStateChangeComplete (149)
/* ns1:AutonomousDUStateChangeComplete */
struct _ns1__AutonomousDUStateChangeComplete
{
	int __sizeResults;	/* sequence of elements <Results> */
	struct ns1__AutonOpResultStruct *Results;	/* required element of type ns1:AutonOpResultStruct */
};
#endif

#ifndef SOAP_TYPE__ns1__AutonomousDUStateChangeCompleteResponse
#define SOAP_TYPE__ns1__AutonomousDUStateChangeCompleteResponse (152)
/* ns1:AutonomousDUStateChangeCompleteResponse */
struct _ns1__AutonomousDUStateChangeCompleteResponse
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE_ParameterNames
#define SOAP_TYPE_ParameterNames (72)
/* SOAP encoded array of xsd:string schema type: */
struct ParameterNames
{
	char **__ptrstring;
	int __size;
};
#endif

#ifndef SOAP_TYPE_ParameterValueList
#define SOAP_TYPE_ParameterValueList (67)
/* SOAP encoded array of ns1:ParameterValueStruct schema type: */
struct ParameterValueList
{
	struct ns1__ParameterValueStruct **__ptrParameterValueStruct;
	int __size;
};
#endif

#ifndef SOAP_TYPE_MethodList
#define SOAP_TYPE_MethodList (64)
/* SOAP encoded array of xsd:string schema type: */
struct MethodList
{
	char **__ptrstring;
	int __size;
};
#endif

#ifndef SOAP_TYPE_EventList
#define SOAP_TYPE_EventList (132)
/* SOAP encoded array of ns1:EventStruct schema type: */
struct EventList
{
	struct ns1__EventStruct **__ptrEventStruct;
	int __size;
};
#endif

#ifndef SOAP_TYPE_ParameterInfoList
#define SOAP_TYPE_ParameterInfoList (77)
/* SOAP encoded array of ns1:ParameterInfoStruct schema type: */
struct ParameterInfoList
{
	struct ns1__ParameterInfoStruct **__ptrParameterInfoStruct;
	int __size;
};
#endif

#ifndef SOAP_TYPE_AccessList
#define SOAP_TYPE_AccessList (43)
/* SOAP encoded array of ns1:AccessListValueType schema type: */
struct AccessList
{
	enum ns1__AccessListValueType *__ptrstring;
	int __size;
};
#endif

#ifndef SOAP_TYPE_SetParameterAttributesList
#define SOAP_TYPE_SetParameterAttributesList (80)
/* SOAP encoded array of ns1:SetParameterAttributesStruct schema type: */
struct SetParameterAttributesList
{
	struct ns1__SetParameterAttributesStruct **__ptrSetParameterAttributesStruct;
	int __size;
};
#endif

#ifndef SOAP_TYPE_ParameterAttributeList
#define SOAP_TYPE_ParameterAttributeList (85)
/* SOAP encoded array of ns1:ParameterAttributeStruct schema type: */
struct ParameterAttributeList
{
	struct ns1__ParameterAttributeStruct **__ptrParameterAttributeStruct;
	int __size;
};
#endif

#ifndef SOAP_TYPE_TimeWindowList
#define SOAP_TYPE_TimeWindowList (122)
/* SOAP encoded array of ns1:TimeWindowStruct schema type: */
struct TimeWindowList
{
	struct ns1__TimeWindowStruct **__ptrTimeWindowStruct;
	int __size;
};
#endif

#ifndef SOAP_TYPE_TransferList
#define SOAP_TYPE_TransferList (100)
/* SOAP encoded array of ns1:QueuedTransferStruct schema type: */
struct TransferList
{
	struct ns1__QueuedTransferStruct **__ptrQueuedTransferStruct;
	int __size;
};
#endif

#ifndef SOAP_TYPE_AllTransferList
#define SOAP_TYPE_AllTransferList (119)
/* SOAP encoded array of ns1:AllQueuedTransferStruct schema type: */
struct AllTransferList
{
	struct ns1__AllQueuedTransferStruct **__ptrAllQueuedTransferStruct;
	int __size;
};
#endif

#ifndef SOAP_TYPE_ns1__InstallOpStruct
#define SOAP_TYPE_ns1__InstallOpStruct (171)
/* ns1:InstallOpStruct */
struct ns1__InstallOpStruct
{
	char *URL;	/* required element of type xsd:anyURI */
	char *UUID;	/* optional element of type ns1:DeploymentUnitUUID */
	char **Username;	/* optional element of type xsd:string */
	char **Password;	/* optional element of type xsd:string */
	char **ExecutionEnvRef;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__UpdateOpStruct
#define SOAP_TYPE_ns1__UpdateOpStruct (172)
/* ns1:UpdateOpStruct */
struct ns1__UpdateOpStruct
{
	char *UUID;	/* optional element of type ns1:DeploymentUnitUUID */
	char **Version;	/* optional element of type xsd:string */
	char **URL;	/* optional element of type xsd:anyURI */
	char **Username;	/* optional element of type xsd:string */
	char **Password;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__UninstallOpStruct
#define SOAP_TYPE_ns1__UninstallOpStruct (174)
/* ns1:UninstallOpStruct */
struct ns1__UninstallOpStruct
{
	char *UUID;	/* required element of type ns1:DeploymentUnitUUID */
	char **Version;	/* optional element of type xsd:string */
	char **ExecutionEnvRef;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__AutonOpResultStruct
#define SOAP_TYPE_ns1__AutonOpResultStruct (150)
/* ns1:AutonOpResultStruct */
struct ns1__AutonOpResultStruct
{
	char *UUID;	/* required element of type ns1:DeploymentUnitUUID */
	char *DeploymentUnitRef;	/* required element of type xsd:string */
	char *Version;	/* required element of type xsd:string */
	enum ns1__DeploymentUnitState CurrentState;	/* required element of type ns1:DeploymentUnitState */
	enum xsd__boolean Resolved;	/* required element of type xsd:boolean */
	char *ExecutionUnitRefList;	/* required element of type xsd:string */
	time_t StartTime;	/* required element of type xsd:dateTime */
	time_t CompleteTime;	/* required element of type xsd:dateTime */
	struct ns1__DeploymentUnitFaultStruct *Fault;	/* required element of type ns1:DeploymentUnitFaultStruct */
	char *OperationPerformed;	/* required element of type ns1:DeploymentUnitOperationType */
};
#endif

#ifndef SOAP_TYPE_VoucherList
#define SOAP_TYPE_VoucherList (105)
/* SOAP encoded array of SOAP-ENC:base64 schema type: */
struct VoucherList
{
	struct SOAP_ENC__base64 **__ptrbase64;
	int __size;
};
#endif

#ifndef SOAP_TYPE_OptionList
#define SOAP_TYPE_OptionList (110)
/* SOAP encoded array of ns1:OptionStruct schema type: */
struct OptionList
{
	struct ns1__OptionStruct **__ptrOptionStruct;
	int __size;
};
#endif

#ifndef SOAP_TYPE_FileTypeArg
#define SOAP_TYPE_FileTypeArg (143)
/* SOAP encoded array of ns1:ArgStruct schema type: */
struct FileTypeArg
{
	struct ns1__ArgStruct **__ptrArgStruct;
	int __size;
};
#endif

#ifndef SOAP_TYPE__ns1__SupportedCWMPVersions
#define SOAP_TYPE__ns1__SupportedCWMPVersions (181)
/* Primitive ns1:SupportedCWMPVersions schema type: */
struct _ns1__SupportedCWMPVersions
{
	char *__item;
	char *SOAP_ENV__mustUnderstand;	/* optional attribute of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__UseCWMPVersion
#define SOAP_TYPE__ns1__UseCWMPVersion (182)
/* Primitive ns1:UseCWMPVersion schema type: */
struct _ns1__UseCWMPVersion
{
	char *__item;
	char *SOAP_ENV__mustUnderstand;	/* required attribute of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__SessionTimeout
#define SOAP_TYPE__ns1__SessionTimeout (183)
/* Primitive ns1:SessionTimeout schema type: */
struct _ns1__SessionTimeout
{
	unsigned int __item;
	char *SOAP_ENV__mustUnderstand;	/* optional attribute of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__ID
#define SOAP_TYPE__ns1__ID (184)
/* Primitive ns1:ID schema type: */
struct _ns1__ID
{
	char *__item;
	char *SOAP_ENV__mustUnderstand;	/* required attribute of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__HoldRequests
#define SOAP_TYPE__ns1__HoldRequests (185)
/* Primitive ns1:HoldRequests schema type: */
struct _ns1__HoldRequests
{
	enum xsd__boolean __item;
	char *SOAP_ENV__mustUnderstand;	/* required attribute of type xsd:string */
};
#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (186)
/* SOAP Header: */
struct SOAP_ENV__Header
{
    struct _ns1__ID *__ID;
    struct _ns1__HoldRequests *__HoldRequests;
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (187)
/* SOAP Fault Code: */
struct SOAP_ENV__Code
{
	char *SOAP_ENV__Value;	/* optional element of type xsd:QName */
	struct SOAP_ENV__Code *SOAP_ENV__Subcode;	/* optional element of type SOAP-ENV:Code */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (189)
/* SOAP-ENV:Detail */
struct SOAP_ENV__Detail
{
	char *__any;
	int __type;	/* any type of element <fault> (defined below) */
	void *fault;	/* transient */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (192)
/* SOAP-ENV:Reason */
struct SOAP_ENV__Reason
{
	char *SOAP_ENV__Text;	/* optional element of type xsd:string */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (193)
/* SOAP Fault: */
struct SOAP_ENV__Fault
{
	char *faultcode;	/* optional element of type xsd:QName */
	char *faultstring;	/* optional element of type xsd:string */
	char *faultactor;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *detail;	/* optional element of type SOAP-ENV:Detail */
	struct SOAP_ENV__Code *SOAP_ENV__Code;	/* optional element of type SOAP-ENV:Code */
	struct SOAP_ENV__Reason *SOAP_ENV__Reason;	/* optional element of type SOAP-ENV:Reason */
	char *SOAP_ENV__Node;	/* optional element of type xsd:string */
	char *SOAP_ENV__Role;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *SOAP_ENV__Detail;	/* optional element of type SOAP-ENV:Detail */
};
#endif

#endif

/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
typedef char *_QName;
#endif

#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (6)
typedef char *_XML;
#endif

#ifndef SOAP_TYPE_xsd__anySimpleType
#define SOAP_TYPE_xsd__anySimpleType (12)
typedef char *xsd__anySimpleType;
#endif

#ifndef SOAP_TYPE_xsd__anyURI
#define SOAP_TYPE_xsd__anyURI (13)
typedef char *xsd__anyURI;
#endif

#ifndef SOAP_TYPE_ns1__DeploymentUnitOperationType
#define SOAP_TYPE_ns1__DeploymentUnitOperationType (14)
typedef char *ns1__DeploymentUnitOperationType;
#endif

#ifndef SOAP_TYPE_ns1__CPEFaultCodeType
#define SOAP_TYPE_ns1__CPEFaultCodeType (15)
typedef unsigned int ns1__CPEFaultCodeType;
#endif

#ifndef SOAP_TYPE_ns1__CPEExtensionFaultCodeType
#define SOAP_TYPE_ns1__CPEExtensionFaultCodeType (16)
typedef unsigned int ns1__CPEExtensionFaultCodeType;
#endif

#ifndef SOAP_TYPE_ns1__CPEVendorFaultCodeType
#define SOAP_TYPE_ns1__CPEVendorFaultCodeType (17)
typedef unsigned int ns1__CPEVendorFaultCodeType;
#endif

#ifndef SOAP_TYPE_ns1__ACSFaultCodeType
#define SOAP_TYPE_ns1__ACSFaultCodeType (18)
typedef unsigned int ns1__ACSFaultCodeType;
#endif

#ifndef SOAP_TYPE_ns1__ACSVendorFaultCodeType
#define SOAP_TYPE_ns1__ACSVendorFaultCodeType (19)
typedef unsigned int ns1__ACSVendorFaultCodeType;
#endif

#ifndef SOAP_TYPE_ns1__TransferFileType
#define SOAP_TYPE_ns1__TransferFileType (20)
typedef char *ns1__TransferFileType;
#endif

#ifndef SOAP_TYPE_ns1__DownloadFileType
#define SOAP_TYPE_ns1__DownloadFileType (21)
typedef char *ns1__DownloadFileType;
#endif

#ifndef SOAP_TYPE_ns1__UploadFileType
#define SOAP_TYPE_ns1__UploadFileType (22)
typedef char *ns1__UploadFileType;
#endif

#ifndef SOAP_TYPE_ns1__EventCodeType
#define SOAP_TYPE_ns1__EventCodeType (23)
typedef char *ns1__EventCodeType;
#endif

#ifndef SOAP_TYPE_ns1__TimeWindowModeValueType
#define SOAP_TYPE_ns1__TimeWindowModeValueType (24)
typedef char *ns1__TimeWindowModeValueType;
#endif

#ifndef SOAP_TYPE_ns1__CommandKeyType
#define SOAP_TYPE_ns1__CommandKeyType (25)
typedef char *ns1__CommandKeyType;
#endif

#ifndef SOAP_TYPE_ns1__ObjectNameType
#define SOAP_TYPE_ns1__ObjectNameType (26)
typedef char *ns1__ObjectNameType;
#endif

#ifndef SOAP_TYPE_ns1__ParameterKeyType
#define SOAP_TYPE_ns1__ParameterKeyType (27)
typedef char *ns1__ParameterKeyType;
#endif

#ifndef SOAP_TYPE_ns1__DeploymentUnitUUID
#define SOAP_TYPE_ns1__DeploymentUnitUUID (31)
typedef char *ns1__DeploymentUnitUUID;
#endif


/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


#ifdef __cplusplus
}
#endif

#endif

/* End of soapStub.h */
